create extension if not exists pgcrypto with schema extensions;

create or replace function private.is_valid_community_layout(p_layout text[])
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    coalesce(array_ndims(p_layout) = 1, false)
    and coalesce(cardinality(p_layout) = 10, false)
    and coalesce(bool_and(coalesce(
      octet_length(row_text) = 13
      and row_text ~ '^[.WOCGRBPYSX]{13}$',
      false
    )), false)
    and coalesce(sum(
      char_length(regexp_replace(row_text, '[.X]', '', 'g'))
    ), 0) >= 8
    and coalesce(sum(
      char_length(regexp_replace(row_text, '[.]', '', 'g'))
    ), 0) <= 100
  from unnest(p_layout) as rows(row_text);
$$;

revoke all on function private.is_valid_community_layout(text[])
  from public, anon, authenticated;

create table public.community_levels (
  id text primary key,
  schema_version smallint not null,
  level_name text not null,
  creator_display_name text not null,
  layout text[] not null,
  populated_count smallint not null,
  content_hash text not null unique,
  created_at timestamptz not null default now(),
  constraint community_levels_id_format
    check (id ~ '^cl_[0-9a-f]{24}$'),
  constraint community_levels_schema_version
    check (schema_version = 1),
  constraint community_levels_level_name
    check (
      char_length(level_name) between 2 and 32
      and level_name ~ '^[A-Z0-9 @._-]+$'
      and level_name = upper(
        regexp_replace(btrim(level_name), '[[:space:]]+', ' ', 'g')
      )
    ),
  constraint community_levels_creator_name
    check (
      char_length(creator_display_name) between 2 and 24
      and creator_display_name ~ '^[A-Z0-9 @._-]+$'
      and creator_display_name = upper(
        regexp_replace(
          btrim(creator_display_name),
          '[[:space:]]+',
          ' ',
          'g'
        )
      )
    ),
  constraint community_levels_layout
    check (private.is_valid_community_layout(layout)),
  constraint community_levels_populated_count
    check (populated_count between 8 and 100),
  constraint community_levels_content_hash
    check (content_hash ~ '^[0-9a-f]{64}$'),
  constraint community_levels_id_matches_hash
    check (id = 'cl_' || left(content_hash, 24))
);

create table private.community_level_moderation (
  level_id text primary key
    references public.community_levels(id),
  status text not null default 'pending',
  actor text not null default 'submission',
  reason text,
  status_changed_at timestamptz not null default now(),
  constraint community_level_moderation_status
    check (status in ('pending', 'listed', 'quarantined', 'removed')),
  constraint community_level_moderation_actor
    check (char_length(actor) between 1 and 128),
  constraint community_level_moderation_reason
    check (reason is null or char_length(reason) between 1 and 1000)
);

create table private.community_level_moderation_events (
  id bigint generated by default as identity primary key,
  level_id text not null references public.community_levels(id),
  previous_status text,
  new_status text not null,
  actor text not null,
  reason text,
  changed_at timestamptz not null default now(),
  constraint community_level_moderation_events_previous_status
    check (
      previous_status is null
      or previous_status in ('pending', 'listed', 'quarantined', 'removed')
    ),
  constraint community_level_moderation_events_new_status
    check (new_status in ('pending', 'listed', 'quarantined', 'removed')),
  constraint community_level_moderation_events_actor
    check (char_length(actor) between 1 and 128),
  constraint community_level_moderation_events_reason
    check (reason is null or char_length(reason) between 1 and 1000)
);

create table private.community_level_submission_limits (
  key_hash text primary key,
  window_started_at timestamptz not null,
  attempt_count integer not null,
  constraint community_level_submission_limits_key_hash
    check (key_hash ~ '^[0-9a-f]{64}$'),
  constraint community_level_submission_limits_attempt_count
    check (attempt_count between 1 and 32767)
);

alter table public.community_levels enable row level security;
alter table private.community_level_moderation enable row level security;
alter table private.community_level_moderation_events enable row level security;
alter table private.community_level_submission_limits enable row level security;

revoke all on table public.community_levels
  from public, anon, authenticated;
revoke all on table private.community_level_moderation
  from public, anon, authenticated;
revoke all on table private.community_level_moderation_events
  from public, anon, authenticated;
revoke all on table private.community_level_submission_limits
  from public, anon, authenticated;
revoke all on sequence private.community_level_moderation_events_id_seq
  from public, anon, authenticated;

create index community_levels_catalog_order_idx
  on public.community_levels (created_at desc, id desc);
create index community_level_moderation_visible_idx
  on private.community_level_moderation (status, level_id)
  where status in ('pending', 'listed');
create index community_level_moderation_events_level_idx
  on private.community_level_moderation_events (level_id, changed_at desc);
create index community_level_submission_limits_window_idx
  on private.community_level_submission_limits (window_started_at);

create function private.reject_community_level_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'community level content is immutable' using errcode = '55000';
end;
$$;

revoke all on function private.reject_community_level_mutation()
  from public, anon, authenticated;

create trigger community_levels_immutable
before update on public.community_levels
for each row execute function private.reject_community_level_mutation();

create function public.submit_community_level(
  p_schema_version integer,
  p_level_name text,
  p_creator_display_name text,
  p_layout text[]
)
returns table(level_id text, created boolean, status text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_level_name text := upper(
    regexp_replace(btrim(p_level_name), '[[:space:]]+', ' ', 'g')
  );
  normalized_creator_name text := upper(
    regexp_replace(btrim(p_creator_display_name), '[[:space:]]+', ' ', 'g')
  );
  canonical_text text;
  calculated_hash text;
  calculated_id text;
  inserted_id text;
begin
  if p_schema_version is distinct from 1 then
    raise exception 'schema_version must be 1' using errcode = '22023';
  end if;
  if p_level_name is null then
    raise exception 'level_name is required' using errcode = '22023';
  end if;
  if p_creator_display_name is null then
    raise exception 'creator_display_name is required' using errcode = '22023';
  end if;
  if char_length(normalized_level_name) not between 2 and 32 then
    raise exception 'level_name must contain 2 to 32 characters'
      using errcode = '22023';
  end if;
  if normalized_level_name !~ '^[A-Z0-9 @._-]+$' then
    raise exception 'level_name contains unsupported characters'
      using errcode = '22023';
  end if;
  if char_length(normalized_creator_name) not between 2 and 24 then
    raise exception 'creator_display_name must contain 2 to 24 characters'
      using errcode = '22023';
  end if;
  if normalized_creator_name !~ '^[A-Z0-9 @._-]+$' then
    raise exception 'creator_display_name contains unsupported characters'
      using errcode = '22023';
  end if;
  if not private.is_valid_community_layout(p_layout) then
    raise exception 'layout must be a valid 13 by 10 community level'
      using errcode = '22023';
  end if;

  canonical_text :=
    '1' || E'\n'
    || normalized_level_name || E'\n'
    || normalized_creator_name || E'\n'
    || array_to_string(p_layout, E'\n');
  calculated_hash := encode(
    extensions.digest(convert_to(canonical_text, 'UTF8'), 'sha256'),
    'hex'
  );
  calculated_id := 'cl_' || left(calculated_hash, 24);

  insert into public.community_levels (
    id,
    schema_version,
    level_name,
    creator_display_name,
    layout,
    populated_count,
    content_hash
  )
  values (
    calculated_id,
    1,
    normalized_level_name,
    normalized_creator_name,
    p_layout,
    (
      select sum(char_length(regexp_replace(row_text, '[.]', '', 'g')))::smallint
      from unnest(p_layout) as rows(row_text)
    ),
    calculated_hash
  )
  on conflict (content_hash) do nothing
  returning id into inserted_id;

  if inserted_id is not null then
    insert into private.community_level_moderation (
      level_id,
      status,
      actor
    )
    values (inserted_id, 'pending', 'submission');

    insert into private.community_level_moderation_events (
      level_id,
      previous_status,
      new_status,
      actor
    )
    values (inserted_id, null, 'pending', 'submission');

    return query select inserted_id, true, 'pending'::text;
    return;
  end if;

  return query
  select
    existing.id,
    false,
    case
      when moderation.status in ('pending', 'listed') then moderation.status
      else 'unavailable'
    end
  from public.community_levels as existing
  join private.community_level_moderation as moderation
    on moderation.level_id = existing.id
  where existing.content_hash = calculated_hash;
end;
$$;

create function public.get_community_levels(
  p_limit integer default 50,
  p_id text default null
)
returns table(
  id text,
  schema_version smallint,
  level_name text,
  creator_display_name text,
  layout text[],
  populated_count smallint,
  created_at timestamptz,
  status text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_limit is null or p_limit not between 1 and 100 then
    raise exception 'limit must be between 1 and 100' using errcode = '22023';
  end if;
  if p_id is not null and p_id !~ '^cl_[0-9a-f]{24}$' then
    raise exception 'id is invalid' using errcode = '22023';
  end if;

  return query
  select
    level.id,
    level.schema_version,
    level.level_name,
    level.creator_display_name,
    level.layout,
    level.populated_count,
    level.created_at,
    moderation.status
  from public.community_levels as level
  join private.community_level_moderation as moderation
    on moderation.level_id = level.id
  where moderation.status in ('pending', 'listed')
    and (p_id is null or level.id = p_id)
  order by level.created_at desc, level.id desc
  limit p_limit;
end;
$$;

create function public.moderate_community_level(
  p_level_id text,
  p_new_status text,
  p_actor text,
  p_reason text default null
)
returns table(
  level_id text,
  previous_status text,
  status text,
  actor text,
  reason text,
  status_changed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_status text;
  normalized_actor text := btrim(p_actor);
  normalized_reason text := nullif(btrim(p_reason), '');
  changed_at timestamptz := clock_timestamp();
begin
  if p_level_id is null or p_level_id !~ '^cl_[0-9a-f]{24}$' then
    raise exception 'level_id is invalid' using errcode = '22023';
  end if;
  if p_new_status is null
    or p_new_status not in ('pending', 'listed', 'quarantined', 'removed')
  then
    raise exception 'moderation status is invalid' using errcode = '22023';
  end if;
  if normalized_actor is null
    or char_length(normalized_actor) not between 1 and 128
  then
    raise exception 'actor must contain 1 to 128 characters'
      using errcode = '22023';
  end if;
  if normalized_reason is not null
    and char_length(normalized_reason) > 1000
  then
    raise exception 'reason must contain at most 1000 characters'
      using errcode = '22023';
  end if;
  if p_new_status in ('quarantined', 'removed') and normalized_reason is null then
    raise exception 'reason is required for quarantined or removed levels'
      using errcode = '22023';
  end if;

  select moderation.status into current_status
  from private.community_level_moderation as moderation
  where moderation.level_id = p_level_id
  for update;

  if current_status is null then
    raise exception 'community level was not found' using errcode = 'P0002';
  end if;
  if not (
    (current_status = 'pending'
      and p_new_status in ('listed', 'quarantined', 'removed'))
    or (current_status = 'listed'
      and p_new_status in ('quarantined', 'removed'))
    or (current_status = 'quarantined'
      and p_new_status in ('pending', 'listed', 'removed'))
  ) then
    raise exception 'moderation transition from % to % is not allowed',
      current_status,
      p_new_status
      using errcode = '22023';
  end if;

  update private.community_level_moderation as moderation
  set
    status = p_new_status,
    actor = normalized_actor,
    reason = normalized_reason,
    status_changed_at = changed_at
  where moderation.level_id = p_level_id;

  insert into private.community_level_moderation_events (
    level_id,
    previous_status,
    new_status,
    actor,
    reason,
    changed_at
  )
  values (
    p_level_id,
    current_status,
    p_new_status,
    normalized_actor,
    normalized_reason,
    changed_at
  );

  return query
  select
    p_level_id,
    current_status,
    p_new_status,
    normalized_actor,
    normalized_reason,
    changed_at;
end;
$$;

create function public.consume_community_level_rate_limit(p_key_hash text)
returns table(allowed boolean, retry_after_seconds integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_time timestamptz := clock_timestamp();
  current_count integer;
  current_window timestamptz;
begin
  if p_key_hash is null or p_key_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'rate-limit key must be a SHA-256 digest'
      using errcode = '22023';
  end if;

  delete from private.community_level_submission_limits as old_limit
  where old_limit.window_started_at < current_time - interval '2 hours'
    and old_limit.key_hash <> p_key_hash;

  insert into private.community_level_submission_limits (
    key_hash,
    window_started_at,
    attempt_count
  )
  values (p_key_hash, current_time, 1)
  on conflict (key_hash) do update
  set
    window_started_at = case
      when private.community_level_submission_limits.window_started_at
        <= current_time - interval '1 hour'
      then current_time
      else private.community_level_submission_limits.window_started_at
    end,
    attempt_count = case
      when private.community_level_submission_limits.window_started_at
        <= current_time - interval '1 hour'
      then 1
      else least(
        private.community_level_submission_limits.attempt_count + 1,
        32767
      )
    end
  returning attempt_count, window_started_at
  into current_count, current_window;

  return query
  select
    current_count <= 5,
    case
      when current_count <= 5 then 0
      else greatest(
        1,
        ceil(extract(
          epoch from (current_window + interval '1 hour' - current_time)
        ))::integer
      )
    end;
end;
$$;

revoke execute on function public.submit_community_level(
  integer,
  text,
  text,
  text[]
) from public, anon, authenticated;
revoke execute on function public.get_community_levels(integer, text)
  from public, anon, authenticated;
revoke execute on function public.moderate_community_level(
  text,
  text,
  text,
  text
) from public, anon, authenticated;
revoke execute on function public.consume_community_level_rate_limit(text)
  from public, anon, authenticated;

grant execute on function public.submit_community_level(
  integer,
  text,
  text,
  text[]
) to service_role;
grant execute on function public.get_community_levels(integer, text)
  to service_role;
grant execute on function public.moderate_community_level(
  text,
  text,
  text,
  text
) to service_role;
grant execute on function public.consume_community_level_rate_limit(text)
  to service_role;

comment on table public.community_levels is
  'Immutable canonical community level content; visibility is RPC-mediated.';
comment on table private.community_level_moderation is
  'Current moderation state for immutable community level content.';
comment on table private.community_level_moderation_events is
  'Append-only community level moderation transition audit trail.';
comment on table private.community_level_submission_limits is
  'HMAC-hashed anonymous network identifiers for five-per-hour throttling.';
