create table public.scores (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  player_name text not null,
  score integer not null,
  outcome text not null,
  completed_stage smallint not null,
  submitted_at timestamptz not null default now(),
  constraint scores_player_name_length check (
    char_length(player_name) between 1 and 16
  ),
  constraint scores_player_name_characters check (
    player_name ~ '^[A-Z0-9@_. -]+$'
  ),
  constraint scores_score_range check (score between 0 and 217290),
  constraint scores_outcome check (
    outcome in ('game_over', 'campaign_clear')
  ),
  constraint scores_completed_stage_range check (
    completed_stage between 1 and 33
  ),
  constraint scores_campaign_completion check (
    outcome <> 'campaign_clear' or completed_stage = 33
  )
);

comment on table public.scores is
  'Best-effort global leaderboard submissions from Stage 1 campaign runs.';
comment on column public.scores.run_id is
  'Client-generated idempotency key; retries never replace the original score.';

create index scores_leaderboard_order_idx
  on public.scores (score desc, submitted_at asc, id asc);

alter table public.scores enable row level security;
revoke all on table public.scores from public, anon, authenticated;
revoke all on sequence public.scores_id_seq from public, anon, authenticated;

create function public.submit_score(
  p_run_id uuid,
  p_player_name text,
  p_score integer,
  p_outcome text,
  p_completed_stage integer
)
returns table(score_id bigint, created boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_name text := upper(btrim(p_player_name));
  inserted_id bigint;
begin
  if p_run_id is null then
    raise exception 'run_id is required' using errcode = '22023';
  end if;
  if char_length(normalized_name) not between 1 and 16 then
    raise exception 'player_name must contain 1 to 16 characters'
      using errcode = '22023';
  end if;
  if normalized_name !~ '^[A-Z0-9@_. -]+$' then
    raise exception 'player_name contains unsupported characters'
      using errcode = '22023';
  end if;
  if p_score not between 0 and 217290 then
    raise exception 'score is outside the campaign range'
      using errcode = '22023';
  end if;
  if p_outcome not in ('game_over', 'campaign_clear') then
    raise exception 'outcome is invalid' using errcode = '22023';
  end if;
  if p_completed_stage not between 1 and 33 then
    raise exception 'completed_stage must be between 1 and 33'
      using errcode = '22023';
  end if;
  if p_outcome = 'campaign_clear' and p_completed_stage <> 33 then
    raise exception 'campaign_clear requires completed_stage 33'
      using errcode = '22023';
  end if;

  insert into public.scores (
    run_id,
    player_name,
    score,
    outcome,
    completed_stage
  )
  values (
    p_run_id,
    normalized_name,
    p_score,
    p_outcome,
    p_completed_stage
  )
  on conflict (run_id) do nothing
  returning id into inserted_id;

  if inserted_id is not null then
    return query select inserted_id, true;
    return;
  end if;

  return query
  select existing.id, false
  from public.scores as existing
  where existing.run_id = p_run_id;
end;
$$;

create function public.get_top_scores(p_limit integer default 100)
returns table(
  rank bigint,
  player_name text,
  score integer,
  outcome text,
  completed_stage smallint,
  submitted_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  with ranked as (
    select
      row_number() over (
        order by entry.score desc, entry.submitted_at asc, entry.id asc
      ) as rank,
      entry.player_name,
      entry.score,
      entry.outcome,
      entry.completed_stage,
      entry.submitted_at
    from public.scores as entry
  )
  select
    ranked.rank,
    ranked.player_name,
    ranked.score,
    ranked.outcome,
    ranked.completed_stage,
    ranked.submitted_at
  from ranked
  order by ranked.rank
  limit least(greatest(coalesce(p_limit, 100), 1), 100);
$$;

revoke execute on function public.submit_score(
  uuid,
  text,
  integer,
  text,
  integer
) from public, anon, authenticated;
revoke execute on function public.get_top_scores(integer)
  from public, anon, authenticated;
grant execute on function public.submit_score(
  uuid,
  text,
  integer,
  text,
  integer
) to anon, authenticated;
grant execute on function public.get_top_scores(integer)
  to anon, authenticated;
