create table private.daily_cartridges (
  daily_id date primary key,
  level_id text not null references public.community_levels(id),
  run_seed integer not null check (run_seed between 0 and 2147483647),
  max_score integer not null check (max_score between 0 and 50000),
  created_at timestamptz not null default now()
);

create table private.daily_run_tickets (
  run_id uuid primary key,
  daily_id date not null references private.daily_cartridges(daily_id),
  level_id text not null references public.community_levels(id),
  token_hash text not null check (token_hash ~ '^[0-9a-f]{64}$'),
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz
);

create table public.daily_scores (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  daily_id date not null references private.daily_cartridges(daily_id),
  level_id text not null references public.community_levels(id),
  player_name text not null,
  score integer not null,
  outcome text not null,
  submitted_at timestamptz not null default now(),
  constraint daily_scores_player_name
    check (
      char_length(player_name) between 2 and 16
      and player_name ~ '^@[A-Z0-9_]{1,15}$'
    ),
  constraint daily_scores_score check (score between 0 and 50000),
  constraint daily_scores_outcome
    check (outcome in ('game_over', 'daily_clear'))
);

alter table private.daily_cartridges enable row level security;
alter table private.daily_run_tickets enable row level security;
alter table public.daily_scores enable row level security;

revoke all on table private.daily_cartridges
  from public, anon, authenticated;
revoke all on table private.daily_run_tickets
  from public, anon, authenticated;
revoke all on table public.daily_scores
  from public, anon, authenticated;
revoke all on sequence public.daily_scores_id_seq
  from public, anon, authenticated;

create index daily_run_tickets_expiry_idx
  on private.daily_run_tickets (expires_at);
create index daily_scores_board_idx
  on public.daily_scores (
    daily_id,
    score desc,
    submitted_at asc,
    id asc
  );
create index daily_scores_player_idx
  on public.daily_scores (
    daily_id,
    player_name,
    score desc,
    submitted_at asc,
    id asc
  );

create function private.daily_level_max_score(p_layout text[])
returns integer
language sql
immutable
strict
set search_path = ''
as $$
  with cells as (
    select substr(rows.row_text, positions.position, 1) as code
    from unnest(p_layout) as rows(row_text)
    cross join lateral generate_series(
      1,
      char_length(rows.row_text)
    ) as positions(position)
  ),
  totals as (
    select
      coalesce(sum(
        case code
          when 'W' then 50
          when 'O' then 60
          when 'C' then 70
          when 'G' then 80
          when 'R' then 90
          when 'B' then 100
          when 'P' then 110
          when 'Y' then 120
          when 'S' then 50
          else 0
        end
      ), 0)::integer as brick_score,
      count(*) filter (where code not in ('.', 'X'))::integer
        as destructible_count
    from cells
  )
  select
    totals.brick_score
    + least(
      8,
      greatest(2, (totals.destructible_count + 4) / 8)
    ) * 100
  from totals;
$$;

create function private.ensure_daily_cartridge(p_daily_id date)
returns private.daily_cartridges
language plpgsql
security definer
set search_path = ''
as $$
declare
  utc_today date := (clock_timestamp() at time zone 'UTC')::date;
  assignment private.daily_cartridges%rowtype;
  selected_level public.community_levels%rowtype;
  seed_value integer;
begin
  if p_daily_id is null or p_daily_id <> utc_today then
    raise exception 'daily cartridge can only be created for today'
      using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('daily:' || p_daily_id::text, 0)
  );

  select existing.* into assignment
  from private.daily_cartridges as existing
  where existing.daily_id = p_daily_id;
  if found then
    return assignment;
  end if;

  select level.* into selected_level
  from public.community_levels as level
  join private.community_level_moderation as moderation
    on moderation.level_id = level.id
  where moderation.status in ('pending', 'listed')
  order by
    (moderation.status = 'listed') desc,
    md5('tinynoid-daily:v1:' || p_daily_id::text || ':' || level.id),
    level.created_at asc,
    level.id asc
  limit 1;

  if selected_level.id is null then
    raise exception 'daily_cartridge_unavailable' using errcode = 'P0001';
  end if;

  seed_value := (
    (
      ('x' || substr(md5(
        'tinynoid-daily-seed:v1:'
        || p_daily_id::text
        || ':'
        || selected_level.id
      ), 1, 8))::bit(32)::bigint
    ) & 2147483647
  )::integer;

  insert into private.daily_cartridges (
    daily_id,
    level_id,
    run_seed,
    max_score
  )
  values (
    p_daily_id,
    selected_level.id,
    seed_value,
    private.daily_level_max_score(selected_level.layout)
  )
  returning * into assignment;

  return assignment;
end;
$$;

create function public.get_daily_cartridge(p_daily_id date default null)
returns table(
  daily_id date,
  opens_at timestamptz,
  closes_at timestamptz,
  accept_until timestamptz,
  run_seed integer,
  max_score integer,
  id text,
  schema_version smallint,
  level_name text,
  creator_display_name text,
  layout text[],
  populated_count smallint,
  created_at timestamptz,
  status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  utc_today date := (clock_timestamp() at time zone 'UTC')::date;
  requested_day date := coalesce(p_daily_id, utc_today);
  assignment private.daily_cartridges%rowtype;
begin
  if requested_day > utc_today then
    raise exception 'future daily cartridges are unavailable'
      using errcode = '22023';
  end if;

  if requested_day = utc_today then
    assignment := private.ensure_daily_cartridge(requested_day);
  else
    select existing.* into assignment
    from private.daily_cartridges as existing
    where existing.daily_id = requested_day;
  end if;

  if assignment.daily_id is null then
    return;
  end if;

  return query
  select
    assignment.daily_id,
    assignment.daily_id::timestamp at time zone 'UTC',
    (assignment.daily_id + 1)::timestamp at time zone 'UTC',
    (
      (assignment.daily_id + 1)::timestamp at time zone 'UTC'
      + interval '6 hours'
    ),
    assignment.run_seed,
    assignment.max_score,
    level.id,
    level.schema_version,
    level.level_name,
    level.creator_display_name,
    level.layout,
    level.populated_count,
    level.created_at,
    moderation.status
  from public.community_levels as level
  join private.community_level_moderation as moderation
    on moderation.level_id = level.id
  where level.id = assignment.level_id
    and moderation.status in ('pending', 'listed');
end;
$$;

create function public.get_daily_scores(
  p_daily_id date,
  p_limit integer default 100
)
returns table(
  rank bigint,
  player_name text,
  score integer,
  outcome text,
  submitted_at timestamptz,
  competitor_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_daily_id is null then
    raise exception 'daily_id is required' using errcode = '22023';
  end if;
  if p_limit is null or p_limit not between 1 and 100 then
    raise exception 'limit must be between 1 and 100' using errcode = '22023';
  end if;

  return query
  with best as (
    select distinct on (entry.player_name)
      entry.id,
      entry.player_name,
      entry.score,
      entry.outcome,
      entry.submitted_at
    from public.daily_scores as entry
    where entry.daily_id = p_daily_id
    order by
      entry.player_name,
      entry.score desc,
      entry.submitted_at asc,
      entry.id asc
  ),
  ranked as (
    select
      rank() over (
        order by best.score desc, best.submitted_at asc, best.id asc
      ) as rank,
      best.player_name,
      best.score,
      best.outcome,
      best.submitted_at,
      count(*) over () as competitor_count
    from best
  )
  select ranked.*
  from ranked
  order by ranked.rank
  limit p_limit;
end;
$$;

create function private.daily_score_receipt(p_run_id uuid)
returns table(
  rank bigint,
  best_score integer,
  competitor_count bigint,
  personal_best boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with target as (
    select entry.daily_id, entry.player_name
    from public.daily_scores as entry
    where entry.run_id = p_run_id
  ),
  best as (
    select distinct on (entry.player_name)
      entry.id,
      entry.run_id,
      entry.player_name,
      entry.score,
      entry.submitted_at
    from public.daily_scores as entry
    join target on target.daily_id = entry.daily_id
    order by
      entry.player_name,
      entry.score desc,
      entry.submitted_at asc,
      entry.id asc
  ),
  ranked as (
    select
      rank() over (
        order by best.score desc, best.submitted_at asc, best.id asc
      ) as rank,
      best.run_id,
      best.player_name,
      best.score,
      count(*) over () as competitor_count
    from best
  )
  select
    ranked.rank,
    ranked.score,
    ranked.competitor_count,
    ranked.run_id = p_run_id
  from ranked
  join target on target.player_name = ranked.player_name;
$$;

create function public.issue_daily_run(
  p_run_id uuid,
  p_daily_id date,
  p_token_hash text,
  p_rate_key text
)
returns table(
  daily_id date,
  level_id text,
  run_seed integer,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_time timestamptz := clock_timestamp();
  utc_today date := (request_time at time zone 'UTC')::date;
  assignment private.daily_cartridges%rowtype;
  expiry timestamptz;
  charged_count integer;
  existing private.daily_run_tickets%rowtype;
begin
  if p_run_id is null then
    raise exception 'run_id is required' using errcode = '22023';
  end if;
  if p_daily_id is null or p_daily_id <> utc_today then
    raise exception 'daily_id must be today in UTC' using errcode = '22023';
  end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'run token must be a SHA-256 digest'
      using errcode = '22023';
  end if;
  if p_rate_key !~ '^[0-9a-f]{64}$' then
    raise exception 'rate-limit key is invalid' using errcode = '22023';
  end if;

  assignment := private.ensure_daily_cartridge(p_daily_id);
  if not exists (
    select 1
    from private.community_level_moderation as moderation
    where moderation.level_id = assignment.level_id
      and moderation.status in ('pending', 'listed')
  ) then
    raise exception 'daily_cartridge_unavailable' using errcode = 'P0001';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_run_id::text, 0)
  );

  if exists (
    select 1 from public.daily_scores as score where score.run_id = p_run_id
  ) then
    raise exception 'run_id has already been submitted' using errcode = '22023';
  end if;

  select ticket.* into existing
  from private.daily_run_tickets as ticket
  where ticket.run_id = p_run_id;
  if (
    existing.run_id is not null
    and existing.consumed_at is null
    and existing.expires_at > request_time
  ) then
    if (
      existing.token_hash <> p_token_hash
      or existing.daily_id <> p_daily_id
      or existing.level_id <> assignment.level_id
    ) then
      raise exception 'run_id already has a different active ticket'
        using errcode = '22023';
    end if;
    return query
    select
      assignment.daily_id,
      assignment.level_id,
      assignment.run_seed,
      existing.expires_at;
    return;
  end if;

  insert into private.score_ticket_limits as limits (
    key_hash,
    window_started_at,
    attempt_count
  )
  values (p_rate_key, request_time, 1)
  on conflict (key_hash) do update
  set
    window_started_at = case
      when limits.window_started_at <= request_time - interval '1 hour'
      then request_time
      else limits.window_started_at
    end,
    attempt_count = case
      when limits.window_started_at <= request_time - interval '1 hour'
      then 1
      else limits.attempt_count + 1
    end
  where
    limits.window_started_at <= request_time - interval '1 hour'
    or limits.attempt_count < 20
  returning attempt_count into charged_count;

  if charged_count is null then
    raise exception 'daily_run_rate_limit_exceeded' using errcode = 'P0001';
  end if;

  expiry := least(
    request_time + interval '6 hours',
    (
      (p_daily_id + 1)::timestamp at time zone 'UTC'
      + interval '6 hours'
    )
  );
  insert into private.daily_run_tickets (
    run_id,
    daily_id,
    level_id,
    token_hash,
    issued_at,
    expires_at,
    consumed_at
  )
  values (
    p_run_id,
    p_daily_id,
    assignment.level_id,
    p_token_hash,
    request_time,
    expiry,
    null
  )
  on conflict (run_id) do update
  set
    daily_id = excluded.daily_id,
    level_id = excluded.level_id,
    token_hash = excluded.token_hash,
    issued_at = excluded.issued_at,
    expires_at = excluded.expires_at,
    consumed_at = null;

  return query
  select
    assignment.daily_id,
    assignment.level_id,
    assignment.run_seed,
    expiry;
end;
$$;

create function public.submit_daily_score(
  p_run_id uuid,
  p_token_hash text,
  p_rate_key text,
  p_daily_id date,
  p_level_id text,
  p_player_name text,
  p_score integer,
  p_outcome text
)
returns table(
  score_id bigint,
  created boolean,
  rank bigint,
  best_score integer,
  competitor_count bigint,
  personal_best boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_time timestamptz := clock_timestamp();
  normalized_name text := upper(btrim(p_player_name));
  moderation_name text;
  assignment private.daily_cartridges%rowtype;
  ticket private.daily_run_tickets%rowtype;
  existing_id bigint;
  inserted_id bigint;
  charged_count integer;
  receipt record;
begin
  select score.id into existing_id
  from public.daily_scores as score
  where score.run_id = p_run_id;
  if existing_id is not null then
    select * into receipt from private.daily_score_receipt(p_run_id);
    return query select
      existing_id,
      false,
      receipt.rank,
      receipt.best_score,
      receipt.competitor_count,
      receipt.personal_best;
    return;
  end if;

  if p_run_id is null then
    raise exception 'run_id is required' using errcode = '22023';
  end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'run token is invalid' using errcode = '22023';
  end if;
  if p_rate_key !~ '^[0-9a-f]{64}$' then
    raise exception 'rate-limit key is invalid' using errcode = '22023';
  end if;
  if p_level_id !~ '^cl_[0-9a-f]{24}$' then
    raise exception 'level_id is invalid' using errcode = '22023';
  end if;

  select cartridge.* into assignment
  from private.daily_cartridges as cartridge
  where cartridge.daily_id = p_daily_id
    and cartridge.level_id = p_level_id;
  if assignment.daily_id is null then
    raise exception 'daily assignment is invalid' using errcode = '22023';
  end if;
  if request_time > (
    (p_daily_id + 1)::timestamp at time zone 'UTC' + interval '6 hours'
  ) then
    raise exception 'daily submission window has closed' using errcode = '22023';
  end if;
  if not exists (
    select 1
    from private.community_level_moderation as moderation
    where moderation.level_id = p_level_id
      and moderation.status in ('pending', 'listed')
  ) then
    raise exception 'daily cartridge is unavailable' using errcode = '22023';
  end if;

  select run_ticket.* into ticket
  from private.daily_run_tickets as run_ticket
  where run_ticket.run_id = p_run_id
  for update;

  select score.id into existing_id
  from public.daily_scores as score
  where score.run_id = p_run_id;
  if existing_id is not null then
    select * into receipt from private.daily_score_receipt(p_run_id);
    return query select
      existing_id,
      false,
      receipt.rank,
      receipt.best_score,
      receipt.competitor_count,
      receipt.personal_best;
    return;
  end if;

  if (
    ticket.run_id is null
    or ticket.daily_id <> p_daily_id
    or ticket.level_id <> p_level_id
    or ticket.token_hash <> p_token_hash
    or ticket.consumed_at is not null
    or ticket.expires_at <= request_time
  ) then
    raise exception 'daily run ticket is missing, invalid, expired, or used'
      using errcode = '22023';
  end if;

  if char_length(normalized_name) not between 2 and 16 then
    raise exception 'player_name must contain an X handle'
      using errcode = '22023';
  end if;
  if normalized_name !~ '^@[A-Z0-9_]{1,15}$' then
    raise exception 'player_name must be an X handle'
      using errcode = '22023';
  end if;
  moderation_name := translate(
    regexp_replace(normalized_name, '[^A-Z0-9]', '', 'g'),
    '013457',
    'OIEAST'
  );
  if exists (
    select 1
    from private.blocked_player_name_terms as blocked
    where position(blocked.term in moderation_name) > 0
  ) then
    raise exception 'player_name is not allowed' using errcode = '22023';
  end if;
  if p_score < 0 or p_score > assignment.max_score then
    raise exception 'score is outside the daily cartridge range'
      using errcode = '22023';
  end if;
  if p_outcome not in ('game_over', 'daily_clear') then
    raise exception 'outcome is invalid' using errcode = '22023';
  end if;

  insert into private.score_submission_limits as limits (
    key_hash,
    window_started_at,
    attempt_count
  )
  values (p_rate_key, request_time, 1)
  on conflict (key_hash) do update
  set
    window_started_at = case
      when limits.window_started_at <= request_time - interval '1 hour'
      then request_time
      else limits.window_started_at
    end,
    attempt_count = case
      when limits.window_started_at <= request_time - interval '1 hour'
      then 1
      else limits.attempt_count + 1
    end
  where
    limits.window_started_at <= request_time - interval '1 hour'
    or limits.attempt_count < 5
  returning attempt_count into charged_count;
  if charged_count is null then
    raise exception 'daily_score_rate_limit_exceeded' using errcode = 'P0001';
  end if;

  insert into public.daily_scores (
    run_id,
    daily_id,
    level_id,
    player_name,
    score,
    outcome,
    submitted_at
  )
  values (
    p_run_id,
    p_daily_id,
    p_level_id,
    normalized_name,
    p_score,
    p_outcome,
    request_time
  )
  returning id into inserted_id;

  update private.daily_run_tickets
  set consumed_at = request_time
  where run_id = p_run_id;

  select * into receipt from private.daily_score_receipt(p_run_id);
  return query select
    inserted_id,
    true,
    receipt.rank,
    receipt.best_score,
    receipt.competitor_count,
    receipt.personal_best;
end;
$$;

revoke all on function private.daily_level_max_score(text[])
  from public, anon, authenticated;
revoke all on function private.ensure_daily_cartridge(date)
  from public, anon, authenticated;
revoke all on function private.daily_score_receipt(uuid)
  from public, anon, authenticated;

revoke execute on function public.get_daily_cartridge(date)
  from public, anon, authenticated;
revoke execute on function public.get_daily_scores(date, integer)
  from public, anon, authenticated;
revoke execute on function public.issue_daily_run(uuid, date, text, text)
  from public, anon, authenticated;
revoke execute on function public.submit_daily_score(
  uuid,
  text,
  text,
  date,
  text,
  text,
  integer,
  text
) from public, anon, authenticated;

grant execute on function public.get_daily_cartridge(date) to service_role;
grant execute on function public.get_daily_scores(date, integer) to service_role;
grant execute on function public.issue_daily_run(uuid, date, text, text)
  to service_role;
grant execute on function public.submit_daily_score(
  uuid,
  text,
  text,
  date,
  text,
  text,
  integer,
  text
) to service_role;

comment on table private.daily_cartridges is
  'Immutable UTC daily assignments backed by playable community levels.';
comment on table public.daily_scores is
  'Ranked Daily Cartridge attempts; public access is RPC-mediated.';
